name: Conventional Commits

on:
  pull_request:
permissions:
  contents: read

jobs:
  conventional-commits:
    name: Conventional Commits
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.1.0
